name: upwork
channels:
- conda-forge
- nodefaults
dependencies:
- pip=24.3.1
- python=3.12.7
- pip:
  - dvc==3.56.0
  - dvc-gs==3.0.1
  - geonamescache==2.0.0
  - hydra-core==1.3.2
  - joblib==1.4.2
  - levenshtein==0.26.1
  - matplotlib==3.9.2
  - mljar-supervised==1.1.15
  - numpy==1.26.4
  - omegaconf==2.3.0
  - openai==1.54.3
  - openpyxl==3.1.5
  - pandas==2.2.3
  - pre-commit==4.0.1
  - pyarrow==18.1.0
  - python-dotenv==1.0.1
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - seaborn==0.13.2
  - snowflake-connector-python==3.12.4
  - tomli==2.0.2
  - tqdm==4.67.0
  - unidecode==1.3.8
