name: upwork
channels:
- conda-forge
- nodefaults
dependencies:
- pip
- python
- pip:
  - dvc
  - dvc-s3
  - hydra-core
  - joblib
  - matplotlib
  - numpy
  - omegaconf
  - opencv-python
  - openpyxl
  - pandas
  - Pillow
  - pre-commit
  - scikit-learn
  - tomli
  - tqdm
