defaults:
- main
- _self_

data_path: data/clean/clean.csv
embeddings_path: data/embeddings
save_dir: eval/embeddings_dimensionality_reduction_openai
text_columns:
- title
- description
- company_name
- company_description
- company_summary
