defaults:
- main
- _self_

data_path: data/clean/clean.csv
embeddings_path: data/embeddings
save_dir: eval/embeddings_dimensionality_reduction_
text_columns:
- title
- description
- company_name
- company_description
- company_summary

embeddings_model_url: text-embedding-3-small
# other options thenlper/gte-small, thenlper/gte-large, text-embedding-3-small, text-embedding-3-large

max_n_components:
  thenlper/gte-small: 384
  thenlper/gte-large: 1024
  text-embedding-3-small: 1536
  text-embedding-3-large: 3072

batch_size: 1000
