hydra:
  run:
    dir: logs/${hydra.job.name}
  job:
    chdir: false
  output_subdir:
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(levelname)s] - %(message)s'
        datefmt: '%d-%m-%Y %H:%M:%S'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        # relative to the job log directory
        filename: ${hydra.run.dir}/${now:%d-%m-%Y_%H-%M-%S}.log
    loggers:
      httpx: # Suppress HTTP request logs
        level: WARNING
        handlers: []
        propagate: false
      urllib3: # Suppress urllib3 logs
        level: WARNING
        handlers: []
        propagate: false
    root:
      level: INFO
      handlers: [console, file]    # [console, file]
    disable_existing_loggers: false
