defaults:
- main
- _self_


save_dir: models
data_path: data/final/final.parquet
pipeline_path: data/final/pipeline.pkl
target_column: wh_hourly_rate # Available options: wh_total_hours, wh_total_charge, wh_hourly_rate, wh_duration
test_size: 0.2
seed: 42

# model config
automl_params:
  mode: Compete
  ml_task: regression
  eval_metric: mse
  total_time_limit: 7200
  optuna_time_budget: 180
  explain_level: 2
