defaults:
- main
- _self_

data_path: data/final/final.parquet
save_dir: models
files:
  data: ${data_dir}/final.parquet
  pipeline: ${data_dir}/pipeline.pkl

target_column: wh_hourly_rate # Available options: wh_total_hours, wh_total_charge, wh_hourly_rate, wh_duration
test_size: 0.2
seed: 42

# model config
automl_params:
  mode: Compete
  ml_task: regression
  eval_metric: mse
  total_time_limit: 7200
  optuna_time_budget: 180
  explain_level: 2
